version: '3.8'

services:
  local_postgres:
    image: postgres:17.2
    restart: always
    container_name: ${SERVER_NAME}_${MODE}
    hostname: docker_${SERVER_NAME}_${MODE}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      TZ: ${TZ}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data_psql:/var/lib/postgresql/data

volumes:
  data_psql:

